// Auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Chat
export const CHATROOM_CREATED = 'CHATROOM_CREATED';
export const CHATROOM_CREATED_ERROR = 'CHATROOM_CREATED_ERROR';
export const GET_CHATROOMS = 'GET_CHATROOMS';
export const GET_CHATROOMS_ERROR = 'GET_CHATROOMS_ERROR';

export const GET_CHATROOM = 'GET_CHATROOM';
export const GET_CHATROOM_ERROR = 'GET_CHATROOM_ERROR';
